---
- name: Update python-apt and python-pycurl
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-apt
    - python-pycurl

- name: Add the Neo4j apt key
  apt_key: url=http://debian.neo4j.org/neotechnology.gpg.key state=present

- name: Setup Neo4j repository
  apt_repository: repo="deb http://debian.neo4j.org/repo stable/" state=present update_cache=yes

- name: Check Neo4j package is installed
  apt: pkg={{ neo4j_package }}={{ neo4j_package_version }} state=present

- name: Ensure graph DB folder exists
  file: path={{ neo4j_server_database_location }} state=directory owner=neo4j group=adm mode=0755

- name: Configure Neo4j server properties
  template: src=neo4j-server.properties  dest=/etc/neo4j/neo4j-server.properties owner=neo4j group=adm mode=0644
  notify: Restart neo4j

- name: Configure Neo4j server wrapper properties
  template: src=neo4j-wrapper.conf dest=/etc/neo4j/neo4j-wrapper.conf owner=neo4j group=adm mode=0644
  notify: Restart neo4j

- name: Configure Neo4j properties
  template: src=neo4j.properties dest=/etc/neo4j/neo4j.properties owner=neo4j group=adm mode=0644
  notify: Restart neo4j

- name: Ensure open files soft limit is set
  lineinfile: dest=/etc/security/limits.conf regexp="^neo4j\s+soft" line="neo4j   soft    nofile  40000" insertbefore="# End of file" state=present

- name: Ensure open files hard limit is set
  lineinfile: dest=/etc/security/limits.conf regexp="^neo4j\s+hard" line="neo4j   hard    nofile  40000" insertbefore="# End of file" state=present

- name: Ensure limits are enabled
  lineinfile: dest=/etc/pam.d/su  regexp="^(# )?session    required   pam_limits.so" line="session    required   pam_limits.so" state=present

# Restarting manually, vagrant ssh and:
#
#    $ sudo service neo4j-service restart
#     * Restarting Neo4j Graph Database neo4j
#    WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
#    Starting Neo4j Server...WARNING: not changing user
#    process [3362]... waiting for server to be ready......... OK.
#    http://localhost:7474/ is ready.
#
# will still warn about the open files limit because of badly written(?)
# init script, see http://stackoverflow.com/a/28999718/525616

- name: Restart machine to apply the new limits from above
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  become: false

- name: Ensure Neo4j service is enabled and started
  service: name=neo4j-service enabled=yes state=started
